name: Summary-Order
run-name: Summary Order
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build
    steps:
      - if: ${{ success() }}
        shell: bash
        run: |
          echo "### Step: 1" >> $GITHUB_STEP_SUMMARY
      - if: ${{ success() }}
        shell: bash
        run: |
          echo "### Step: 2" >> $GITHUB_STEP_SUMMARY
      - if: ${{ success() }}
        shell: bash
        run: |
          echo "### Step: 3" >> $GITHUB_STEP_SUMMARY
      - if: ${{ success() }}
        shell: bash
        run: |
          echo "### Step: 4" >> $GITHUB_STEP_SUMMARY
      - if: ${{ success() }}
        shell: bash
        run: |
          echo "### Step: 5" >> $GITHUB_STEP_SUMMARY